apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-demo
  namespace: default
spec:
  interval: 30s # How often Flux checks for repository updates (new commits)
  ref:
    branch: piontec-test
  # To learn how to checkout private repositories, check
  # https://fluxcd.io/docs/components/source/gitrepositories/#spec-examples
  url: https://github.com/giantswarm/flux-demo
  timeout: 30s
