apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: install-organization
  namespace: default
spec:
  interval: 30s
  path: ./02-organization
  prune: true
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: flux-demo
  validation: client
