apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: install-managed-app
  namespace: default
spec:
  interval: 30s
  path: ./04-managed-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-demo
  serviceAccountName: automation
  validation: client
