apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: install-organization
  namespace: flux-system
spec:
  interval: 30s
  path: ./02-organization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-demo-development
  validation: client
