apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-demo-development
  namespace: default
spec:
  interval: 30s
  ref:
    branch: development
  url: https://github.com/giantswarm/flux-demo
  timeout: 30s
